name: nv_golden
description: The golden testing framework we use at nonvanilla. Thanks to the people at ebay that strongly inspired this plugin with their golden_toolkit.
version: 0.0.5
homepage: https://github.com/nonvanilla-shop/nonvanilla_testing/
repository: https://github.com/nonvanilla-shop/nonvanilla_testing/tree/master/packages/nv_golden

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    # needed to trigger the FontManifest.json to be included
    - images/
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/nv_golden/fonts/Roboto-Regular.ttf