name: nv_cubit_testing
description: Cubit testing plugin used by NonVanilla. It provides a more
  flexible solution than bloc_test.
version: 0.0.4
homepage: https://github.com/nonvanilla-shop/nonvanilla_testing
repository: https://github.com/nonvanilla-shop/nonvanilla_testing/tree/master/nv_cubit_testing

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  mockito: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
